# Generated by Django 4.2.29 on 2026-07-09 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import src.lib.utils.uuid7


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminConfig',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('fal_api_key', models.CharField(blank=True, default='', max_length=500)),
                ('llm_provider', models.CharField(choices=[('groq', 'Groq'), ('openai', 'OpenAI'), ('gemini', 'Google Gemini'), ('anthropic', 'Anthropic Claude')], default='groq', max_length=50)),
                ('llm_api_key', models.CharField(blank=True, default='', max_length=500)),
                ('llm_model', models.CharField(default='llama-3.1-8b-instant', max_length=100)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('english', models.CharField(max_length=255)),
                ('yoruba', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('animals', 'Animals'), ('colors', 'Colors'), ('numbers', 'Numbers'), ('objects', 'Objects')], max_length=50)),
                ('emoji', models.CharField(max_length=50)),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'vocabularies',
                'ordering': ['date_created'],
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant')], max_length=20)),
                ('text', models.TextField()),
                ('audio_url', models.URLField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoruba_chat_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.UUIDField(default=src.lib.utils.uuid7.uuid7, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('animals', 'Animals'), ('colors', 'Colors'), ('numbers', 'Numbers'), ('objects', 'Objects')], max_length=50)),
                ('stars', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('last_played', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yoruba_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['category'],
                'unique_together': {('user', 'category')},
            },
        ),
    ]
