# Generated by Django 4.2.29 on 2026-07-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoruba_learning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminconfig',
            name='yarn_gpt_api_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='adminconfig',
            name='yarn_gpt_voice',
            field=models.CharField(choices=[('Idera', 'Idera'), ('Emma', 'Emma'), ('Zainab', 'Zainab'), ('Osagie', 'Osagie'), ('Wura', 'Wura'), ('Jude', 'Jude'), ('Chinenye', 'Chinenye'), ('Tayo', 'Tayo'), ('Regina', 'Regina'), ('Femi', 'Femi'), ('Adaora', 'Adaora'), ('Umar', 'Umar'), ('Mary', 'Mary'), ('Nonso', 'Nonso'), ('Remi', 'Remi'), ('Adam', 'Adam')], default='Idera', max_length=50),
        ),
    ]
